apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fake-api-app
  template:
    metadata:
      labels:
        app: fake-api-v2
    spec:
      containers:
        - name: broken-api-container
          image: nginx:nonexistent
          env:
            - name: ENVV
              value: "production"
          envFrom:
            - configMapRef:
                name: missing-config
